spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
 # Relative path for file uploads

